server:
  port: 8765

spring:
  application:
    name: customer-service
  profiles:
    active: local

  data:
    mongodb:
      uri: mongodb://localhost:27017/customer_management

#logs.dir: ..//logs